name: deploy to aws sbox
description: deploy helloword to aws sbox account

inputs:
  NAME:
    description: "RNA name prefix"
    required: false
  TEMPLATE_BUCKET:
    description: "S3 Bucket for CloudFormation deployment artifacts"
    required: true
  STACK_NAME:
    description: "Name of the deployed stack"
    required: true
  DEPLOY_ROLE_ARN:
    description: "role_arn name"
    required: true

runs:
  using: "composite"
  steps:
     - name: install
       shell: bash
       run: |
         sudo apt update
         echo "updated"
         pip install --upgrade pip
         echo "upgraded pip"

     - name: build
       shell: bash
       run: |
         echo "install requirement..." 
         pip3 install -r requirements.txt -t src/

     - name: test s3 access
       shell: bash
       run: |
         echo "test if s3://jzhu4 bucket is accessiable"
         aws s3 ls --recursive ${{ inputs.TEMPLATE_BUCKET }}
     - name: deploy
       shell: bash
       run: |
         echo "aws cloudformation package..."       
         aws cloudformation package \
           --template-file cloudformation.yaml \
           --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
           --output-template-file cloudformation-final.yml
         
         echo "aws cloudformation deploy..."
         aws cloudformation deploy \
            --stack-name ${{ inputs.STACK_NAME }} \
            --template-file cloudformation-final.yml \
            --role-arn ${{ inputs.DEPLOY_ROLE_ARN }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                Name='${{ inputs.NAME }}'
