name: deploy-to-aws-sbox
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "define the aws credentials."
      - uses: actions/checkout@v2
